<?php namespace App\Models\Base;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Right extends AbstractTable {

    /**
     * Generated
     */

    use SoftDeletes;
    const DELETED_AT = 'DeletedAt';

    protected $table = 'Rights';
    protected $fillable = ['Id', 'RightsGroupId', 'Name', 'KeyName', 'Action', 'IsAutoGenerated', 'Excluded', 'Message', 'DeletedAt', 'DeletedBy', 'CreatedAt', 'CreatedBy'];


    public function rightsGroup() {
        return $this->belongsTo(\App\Models\RightsGroup::class, 'RightsGroupId', 'Id');
    }

    public function aspNetRoles() {
        return $this->belongsToMany(\App\Models\AspNetRole::class, 'RoleRights', 'RightId', 'RoleId');
    }

    public function roleRights() {
        return $this->hasMany(\App\Models\RoleRight::class, 'RightId', 'Id');
    }


}
