<?php namespace App\Models\Base;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class RightsGroup extends AbstractTable {

    /**
     * Generated
     */

    use SoftDeletes;
    const DELETED_AT = 'DeletedAt';

    protected $table = 'RightsGroups';
    protected $fillable = ['Id', 'Name', 'Controller', 'IsAutoGenerated', 'Excluded', 'DeletedAt', 'DeletedBy', 'CreatedAt', 'CreatedBy'];


    public function rights() {
        return $this->hasMany(\App\Models\Right::class, 'RightsGroupId', 'Id');
    }


}
