<?php
namespace App\Models;

/**
 * App\Models\Right
 *
 * @property int $Id Id
 * @property int $RightsGroupId
 * @property string|null $Name Название
 * @property string $KeyName
 * @property string $Action Action
 * @property bool $IsAutoGenerated АвтоГенерация
 * @property bool $Excluded Исключен
 * @property string|null $Message
 * @property bool $ExcludedInClientPlace Исключен на продакшене
 * @property string|null $DeletedDate Дата удаления
 * @property string|null $CreatedDate Дата создания
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Base\AbstractTable noLock()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereAction($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereCreatedDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereDeletedDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereExcluded($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereExcludedInClientPlace($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereIsAutoGenerated($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereKeyName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereMessage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereRightsGroupId($value)
 * @mixin \Eloquent
 * @property string|null $DeletedAt Дата удаления
 * @property \Illuminate\Support\Carbon|null $CreatedAt Дата создания
 * @property string $CreatedBy
 * @property string $DeletedBy
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Right whereDeletedBy($value)
 */
class Right extends Base\Right {
	//
}

